//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBaseDeDatos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConexionBaseDeDatos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #CREATE DATABASE IF NOT EXISTS `diamond_dentures` /*!40100 DEFAULT CHARACTER SET utf8 */;
        ///
        ///#USE `diamond_dentures`;
        ///
        ///CREATE TABLE IF NOT EXISTS `dentistas` (
        ///  `Cedula` char(10) NOT NULL,
        ///  `RFC` char(15) NOT NULL,
        ///  `NombreDen` char(50) NOT NULL,
        ///  `ApellidosDen` char(50) NOT NULL,
        ///  `Telefono` char(10) NOT NULL,
        ///  `Pais` char(30) NOT NULL,
        ///  `Estado` char(30) NOT NULL,
        ///  `Municipio` char(50) NOT NULL,
        ///  `Ciudad` char(50) NOT NULL,
        ///  `Colonia` char(30) NOT NULL,
        ///  `Calle` char(80) NOT NULL,
        ///  `NumFrent [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Script_Diamond_dentures {
            get {
                return ResourceManager.GetString("Script_Diamond_dentures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DROP PROCEDURE IF EXISTS `ActivarMaterial`;
        ///CREATE PROCEDURE `ActivarMaterial`(clv int)
        ///BEGIN
        ///  Update `materiales` set
        ///    Activo = 1
        ///    Where Clave = `clv`;
        ///END;
        ///
        ///DROP PROCEDURE IF EXISTS `ActivarProducto`;
        ///CREATE PROCEDURE `ActivarProducto`(
        ///  clv int
        ///)
        ///BEGIN
        ///  Update `productos` set
        ///    Activo = 1
        ///    Where Clave = `clv`;
        ///END;
        ///
        ///DROP PROCEDURE IF EXISTS `ActivarUsuario`;
        ///
        ///CREATE PROCEDURE `ActivarUsuario`(logi varchar(30))
        ///BEGIN
        ///declare maxi int;
        ///select max(`ultima`) into maxi from `tarjetas [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Script_Procedimientos {
            get {
                return ResourceManager.GetString("Script_Procedimientos", resourceCulture);
            }
        }
    }
}
